### ISSUE TITLE
psubscribe wildcards don't work correctly

### ISSUE THREAD

**Issue by jedwards1211** [stipsan/ioredis-mock#1075]
The mock implementation uses `minimatch`, which is not a valid choice because it differs from redis psubscribe pattern behavior in numerous ways.

As a simple example, `*` should match any redis channel, but `minimatch('a/b', '*') === false`.

A little bit of code review on the psubscribe PR should have caught the three issues I've filed so far.

**Comment by stipsan** [comment]
>A little bit of code review on the psubscribe PR should have caught the three issues I've filed so far.

It's years since I worked for an employer that not only use `ioredis` & `ioredis-mock` but also paid for the time spent maintaining the project. All I can do these days is reviewing PRs and ensuring nothing malicious is snuck in, no sketchy 3rd party npm packages and such, and if the new features have tests and they pass then time's up.
I wish I had the time to dig into each PR and ensure they implement features 100% according to spec, but alas, I don't.
I'd be happy to invite you to the project if you're interested in being a maintainer and bring your experience with redis onboard, you'll be able to do a much better job than I in code reviews :)

**Comment by jedwards1211** [comment]
I see, yeah I know how it goes with time management...sorry, I was letting frustration get to me.  I can't promise to have much time either, but I'm willing to help.  (I don't use a lot of Redis features for my work, though I have gotten to know the in and outs of pubsub.)  Some of the issues seem like they'd be simple to fix as well.  And I would definitely try to research commands I'm not familiar with carefully.

**Comment by stipsan** [comment]
No worries @jedwards1211, it's entirely relatable 🙂 I sent you an invite to be a collaborator, it's slightly less annoying to contribute from a branch instead of from a fork 😄
