### ISSUE TITLE
Values Shared Across Instances (5.9.0)

### ISSUE THREAD

**Issue by SE2Dev** [stipsan/ioredis-mock#1113]
As of ioredis-mock@5.9.0, all redis values tracked by ioredis-mock are shared across all instances of RedisMock; this was not the case in previous versions.

Example:

```js
// declare peer dependencies so RunKit don't throw errors
require('ioredis/package.json');
require('redis-commands/package.json');

const Redis = require('ioredis-mock');

const redis0 = new Redis();
const redis1 = new Redis({
  data: {
    hello: "4"
  },
});

async function main() {
  const v0 = await redis0.get("hello");
  const v1 = await redis1.get("hello");
  if(v0 === v1) {
    throw new Error("ioredis-mock leaked values across instances");
  }
}

main();
```

**Comment by stipsan** [comment]
Yes, in hindsight we should've made a breaking major release instead of a minor feature release for this one.

Moving forward you'll need to run `flushall` between each test to get the same behavior as in `v5.8` and older:

```js
import Redis from 'ioredis';

afterEach((done) => {
  new Redis().flushall().then(() => done());
});
```

I'll make a new major release that documents this breaking change. I'll then republish [`v5.8.4`](https://www.npmjs.com/package/ioredis-mock/v/5.8.4) as `v5.9.1` with a note in the readme about the situation. It's always been the intention for this project to follow semver and it's on me that we slipped for this release 🙇

**Comment by stipsan** [comment]
Closing this as:
- The new behavior is intended, and documented in [the readme](https://github.com/stipsan/ioredis-mock#breaking-api-changes-from-v5).
- It's also documented in the release notes for [`v6.0.0`](https://github.com/stipsan/ioredis-mock/releases/tag/v6.0.0).
- The `v5.9.0` is marked as [breaking on GitHub Releases](https://github.com/stipsan/ioredis-mock/releases/tag/v5.9.0), with a note about using `v5.8.4`, `v5.9.1` or `v6.0.0` instead.
- The `v5.9.0` release is marked as [deprecated on npm](https://www.npmjs.com/package/ioredis-mock/v/5.9.0), with the same information as on GitHub.
- The new `v5.9.1` release [on npm ensures](https://www.npmjs.com/package/ioredis-mock/v/5.9.1) people affected by the breaking change in `v5.9.0` by semver, is now getting `v5.8.4` until they opt-in to upgrading to `v6.0.0`.
- The situation is also explained in the `v5.9.1` [release notes](https://github.com/stipsan/ioredis-mock/releases/tag/v5.9.1).
